#!/usr/bin/env bash
# Peer-supervised O1 promotion — host-level deployer v2.
#
# v2 differs from peer_promote_o1.sh in three critical ways, all
# addressing the 2026-08-08 O1 promotion incident:
#
#   1. STAGING IS DETERMINISTIC.
#      The previous script ran ``pip install omnigent[all]`` against
#      live PyPI and let ``pip`` resolve the dependency closure.
#      That failed on ``opentelemetry-instrumentation-fastapi<1,>=0``
#      because the only available releases are 0.x beta. The new
#      script delegates staging to the peer_deployer.staging module,
#      which COPIES the supervisor's site-packages wholesale and
#      installs only the three SDK wheels with ``--no-deps``. Live
#      PyPI is never consulted for any dependency.
#
#   2. STAGING IS PER-TRANSACTION.
#      The previous script staged into
#      ``/opt/omnigent/releases/<sha>`` (the final shared path). Two
#      transactions targeting the same SHA could collide on partial
#      state, and a failed staging left stale partial files at the
#      final location. The new script stages into
#      ``/opt/omnigent/staging/<TX_ID>/`` and only atomically swaps
#      into the final path after every verify step passes.
#
#   3. STAGED-RUNTIME VERIFICATION IS MANDATORY.
#      The previous script crossed the mutation boundary as soon as
#      ``pip install`` returned 0. The new script requires a complete
#      staged runtime to pass ``candidate_runtime_staged_and_verified``
#      BEFORE the transaction is allowed to cross into stop/migrate/
#      switch. If staging fails for any reason, the active O1 runtime,
#      DB, and services are not touched and the rollback subsystem
#      never runs against the active runtime.
#
# The script is intentionally narrow. It cannot upgrade the
# supervisor. It cannot change target/supervisor identity. It cannot
# deploy any artifact other than the exact accepted one. It does not
# weaken the supervisor's sandbox.
#
# This script must be executed by a host-level operator (root) OUTSIDE
# the O2 hermes sandbox. O2 prepares and verifies the command; the
# host-level operator runs it.

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# Configuration — generated by the O2 supervisor session.
# Edit ONLY the operational variables (TX_ROOT, EVIDENCE_DIR). Do not
# change the runtime identity or the wheel hashes.
# ─────────────────────────────────────────────────────────────────────

TARGET="O1"
SUPERVISOR="O2"

ACCEPTED_SHA="541c9a3180b81bfb2fc450b3ef5f8648691b359d"
ACCEPTED_VERSION="0.9.0.dev0"
EXPECTED_MAIN_WHEEL_SHA256="f49fb3f973c1d98be03eaede76e9c7e86acb91064b06494afdf8f7345524a5e9"
EXPECTED_SDK_CLIENT_WHEEL_SHA256="555a6286477bd528005478571b24cd2fda5c9da505f0957d606b6182614f9605"
EXPECTED_SDK_UI_WHEEL_SHA256="e2141bc6af3bee42a85cad1ff48d008d20439ee34cb52956cda1b7fdff1d45a9"
EXPECTED_DB_SCHEMA="f7a8b9c0d1e2"

# Layout.
TARGET_DEPLOY_ROOT="/opt/omnigent"
TARGET_HOME="/var/lib/omnigent"
SUPERVISOR_DEPLOY_ROOT="/opt/omnigent-production"
SUPERVISOR_HOME="/var/lib/omnigent-production"

SOURCE_RELEASE="${SUPERVISOR_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}"
SOURCE_ARTIFACTS="${SOURCE_RELEASE}/artifacts"
SOURCE_MAIN_WHEEL="${SOURCE_ARTIFACTS}/omnigent-${ACCEPTED_VERSION}-py3-none-any.whl"
SOURCE_SDK_CLIENT_WHEEL="${SOURCE_ARTIFACTS}/omnigent_client-${ACCEPTED_VERSION}-py3-none-any.whl"
SOURCE_SDK_UI_WHEEL="${SOURCE_ARTIFACTS}/omnigent_ui_sdk-${ACCEPTED_VERSION}-py3-none-any.whl"

TARGET_SERVER_UNIT="omnigent.service"
TARGET_HOST_UNIT="omnigent-host.service"
SUPERVISOR_SERVER_UNIT="omnigent-production.service"
SUPERVISOR_HOST_UNIT="omnigent-production-host.service"
TARGET_HEALTH_URL="http://127.0.0.1:4097/health"
SUPERVISOR_HEALTH_URL="http://127.0.0.1:4197/health"

# Transaction state.
TX_ROOT="${OMNIGENT_CONTROL_ROOM_TX_ROOT:-/var/lib/omnigent-control-room/transactions}"
EVIDENCE_DIR="${OMNIGENT_CONTROL_ROOM_EVIDENCE_DIR:-/var/lib/omnigent-production/upstream-0.9-candidate-20260808T100458Z/17-peer-deployer-reproducible-staging}"
TX_ID="promotion-$(date -u +%Y%m%dT%H%M%SZ)-$(head -c 4 /dev/urandom | od -An -tx1 | tr -d "\n ")"
TX_DIR="${TX_ROOT}/${TX_ID}"
TARGET_DB="${TARGET_HOME}/chat.db"
DB_BACKUP_DIR="${EVIDENCE_DIR}/tx-${TX_ID}"
DB_BACKUP_PATH="${DB_BACKUP_DIR}/chat.db"

# Per-transaction staging path. Different from the final release path
# so two transactions cannot collide on partial state.
STAGING_ROOT="${TARGET_DEPLOY_ROOT}/staging/${TX_ID}"
# Final shared release path. Only touched after atomic-swap.
FINAL_RELEASE="${TARGET_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}"
FINAL_VENV_LINK="${TARGET_DEPLOY_ROOT}/venv"

# Python helper location. We delegate all staging, verification, and
# rollback logic to the peer_deployer Python package.
PEER_DEPLOYER_DIR="${OMNIGENT_PEER_DEPLOYER_DIR:-/var/lib/omnigent-production/tmp/peer-deployer-worktree/deploy/scripts/peer_deployer}"
PEER_DEPLOYER_RUNNER="${PEER_DEPLOYER_DIR}/__main__.py"

# The system Python is fine for the deployer CLI; staging itself uses
# the candidate venv's interpreter. ensurepip on the system Python is
# what bootstraps pip in the new venv.
SYSTEM_PYTHON="${OMNIGENT_SYSTEM_PYTHON:-/opt/omnigent-production/current/venv/bin/python3.12}"

# ─────────────────────────────────────────────────────────────────────
# Helpers.
# ─────────────────────────────────────────────────────────────────────

log()  { printf '[peer-promote-o1 %s] %s\n' "$TX_ID" "$*" >&2; }
fail() { printf '[peer-promote-o1 %s] FAIL: %s\n' "$TX_ID" "$*" >&2; exit 1; }

sha256() { sha256sum "$1" | awk '{print $1}'; }

# service_state_active <unit>
# Returns 0 iff the unit is in the "active" state. Uses the
# vetted peer-deployer helper to avoid the broken
# `is-active | grep -q` pattern under pipefail.
service_state_active() {
  local unit="$1"
  local state
  state="$(systemctl is-active "$unit" 2>/dev/null || true)"
  state="${state,,}"
  state="${state//[[:space:]]/}"
  [[ "$state" == "active" ]]
}

assert_privilege() {
  if [[ $EUID -ne 0 ]]; then
    fail "must run as root (or under sudo -E)"
  fi
}

assert_supervisor_health() {
  install -d "${EVIDENCE_DIR}"
  install -d "${TX_DIR}"
  log "verifying supervisor health"
  if ! systemctl cat "$SUPERVISOR_SERVER_UNIT" >/dev/null 2>&1; then
    fail "supervisor service unit not installed: $SUPERVISOR_SERVER_UNIT"
  fi
  if ! systemctl cat "$SUPERVISOR_HOST_UNIT" >/dev/null 2>&1; then
    fail "supervisor host unit not installed: $SUPERVISOR_HOST_UNIT"
  fi
  if ! service_state_active "$SUPERVISOR_SERVER_UNIT"; then
    fail "supervisor server is not active: $SUPERVISOR_SERVER_UNIT"
  fi
  if ! service_state_active "$SUPERVISOR_HOST_UNIT"; then
    fail "supervisor host is not active: $SUPERVISOR_HOST_UNIT"
  fi
  if ! curl -fsS --max-time 5 "$SUPERVISOR_HEALTH_URL" >/dev/null 2>&1; then
    fail "supervisor /health not OK: $SUPERVISOR_HEALTH_URL"
  fi
}

assert_supervisor_identity() {
  # Use the import-based helper from peer_deployer.identity so the
  # source form of _build_info.py is irrelevant. This is the fix
  # ported from the manual patch that was applied to peer_promote_o1.sh.
  local actual_sha actual_version
  actual_sha="$(cd /tmp && PYTHONPATH= "${SUPERVISOR_DEPLOY_ROOT}/current/venv/bin/python" -c 'from omnigent._build_info import COMMIT_SHA; print(COMMIT_SHA)')"
  if [[ "$actual_sha" != "$ACCEPTED_SHA" ]]; then
    fail "supervisor installed SHA $actual_sha != accepted $ACCEPTED_SHA"
  fi
  # Read the supervisor's installed version via importlib.metadata
  # (canonical distribution identity). The supervisor's runtime
  # provides this; no source-tree parsing.
  actual_version="$(cd /tmp && PYTHONPATH= "${SUPERVISOR_DEPLOY_ROOT}/current/venv/bin/python" -c 'from importlib.metadata import version; print(version("omnigent"))')"
  if [[ "$actual_version" != "$ACCEPTED_VERSION" ]]; then
    fail "supervisor installed version $actual_version != accepted $ACCEPTED_VERSION"
  fi
  log "supervisor identity verified: $actual_sha / $actual_version"
}

assert_artifact_hashes() {
  if [[ ! -d "$SOURCE_RELEASE" ]]; then
    fail "accepted release dir missing: $SOURCE_RELEASE"
  fi
  if [[ ! -f "$SOURCE_MAIN_WHEEL" ]]; then
    fail "accepted main wheel missing: $SOURCE_MAIN_WHEEL"
  fi
  if [[ ! -f "$SOURCE_SDK_CLIENT_WHEEL" ]]; then
    fail "accepted SDK client wheel missing: $SOURCE_SDK_CLIENT_WHEEL"
  fi
  if [[ ! -f "$SOURCE_SDK_UI_WHEEL" ]]; then
    fail "accepted SDK UI wheel missing: $SOURCE_SDK_UI_WHEEL"
  fi
  local actual
  actual="$(sha256 "$SOURCE_MAIN_WHEEL")"
  [[ "$actual" == "$EXPECTED_MAIN_WHEEL_SHA256" ]] || fail "main wheel SHA mismatch: $actual"
  actual="$(sha256 "$SOURCE_SDK_CLIENT_WHEEL")"
  [[ "$actual" == "$EXPECTED_SDK_CLIENT_WHEEL_SHA256" ]] || fail "SDK client wheel SHA mismatch: $actual"
  actual="$(sha256 "$SOURCE_SDK_UI_WHEEL")"
  [[ "$actual" == "$EXPECTED_SDK_UI_WHEEL_SHA256" ]] || fail "SDK UI wheel SHA mismatch: $actual"
  log "all three wheel SHA-256 verified"
}

assert_target_distinct_from_supervisor() {
  if [[ "$TARGET" == "$SUPERVISOR" ]]; then
    fail "REFUSED: target == supervisor == $TARGET"
  fi
  if [[ "$TARGET_DEPLOY_ROOT" == "$SUPERVISOR_DEPLOY_ROOT" ]]; then
    fail "REFUSED: target and supervisor share deploy root"
  fi
  if [[ "$TARGET_HOME" == "$SUPERVISOR_HOME" ]]; then
    fail "REFUSED: target and supervisor share home"
  fi
  if [[ "$TARGET_SERVER_UNIT" == "$SUPERVISOR_SERVER_UNIT" ]]; then
    fail "REFUSED: target and supervisor share service unit"
  fi
  log "target ($TARGET) != supervisor ($SUPERVISOR)"
}

snapshot_supervisor_state() {
  local out="$1"
  : > "$out"
  for unit in "$SUPERVISOR_SERVER_UNIT" "$SUPERVISOR_HOST_UNIT"; do
    systemctl show "$unit" -p MainPID -p NRestarts -p ActiveEnterTimestampMonotonic \
      -p ActiveEnterTimestamp -p ActiveState >> "$out" 2>&1 || return 1
  done
}

create_transaction_record() {
  local provenance
  provenance="${SOURCE_RELEASE}/PROVENANCE.txt"
  if [[ ! -f "$provenance" ]]; then
    fail "PROVENANCE.txt missing: $provenance"
  fi
  cat > "${TX_DIR}/transaction.json" <<JSON
{
  "tx_id": "${TX_ID}",
  "target": "${TARGET}",
  "supervisor": "${SUPERVISOR}",
  "target_artifact_sha": "${ACCEPTED_SHA}",
  "target_artifact_version": "${ACCEPTED_VERSION}",
  "main_wheel_sha256": "${EXPECTED_MAIN_WHEEL_SHA256}",
  "sdk_client_wheel_sha256": "${EXPECTED_SDK_CLIENT_WHEEL_SHA256}",
  "sdk_ui_wheel_sha256": "${EXPECTED_SDK_UI_WHEEL_SHA256}",
  "created_at_unix": $(date +%s),
  "phase": "init",
  "mutation_boundary_crossed": false,
  "old_runtime_path": "${TARGET_DEPLOY_ROOT}/venv",
  "old_runtime_sha": "$(cd /tmp && PYTHONPATH= "${TARGET_DEPLOY_ROOT}/venv/bin/python" -c 'from omnigent._build_info import COMMIT_SHA; print(COMMIT_SHA)' 2>/dev/null)",
  "old_runtime_version": "0.8.1",
  "new_runtime_path": "${FINAL_RELEASE}",
  "new_runtime_sha": "${ACCEPTED_SHA}",
  "new_runtime_version": "${ACCEPTED_VERSION}",
  "db_backup_path": "${DB_BACKUP_PATH}",
  "db_backup_sha256": "",
  "db_backup_integrity": "",
  "old_db_schema": "c4d5e6f7a8b9",
  "target_db_schema": "${EXPECTED_DB_SCHEMA}",
  "owned_resources": [
    "${STAGING_ROOT}",
    "${FINAL_RELEASE}",
    "${EVIDENCE_DIR}/tx-${TX_ID}/promotion.log",
    "${EVIDENCE_DIR}/tx-${TX_ID}/chat.db"
  ],
  "log_path": "${EVIDENCE_DIR}/tx-${TX_ID}/promotion.log",
  "rollback_reason": "",
  "rollback_completed": false
}
JSON
  install -d "${EVIDENCE_DIR}/tx-${TX_ID}"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"
}

# tx_write_json <python-expression-on-tx_dir-and-tx_id>
# Runs an inline Python snippet that mutates the transaction record.
# The snippet receives ``tx_dir`` and ``tx_id`` in scope.
tx_write_json() {
  local expr="$1"
  SYSTEM_PYTHON="$SYSTEM_PYTHON" python3 -c "
import json, os
p = '${TX_DIR}/transaction.json'
d = json.load(open(p))
${expr}
json.dump(d, open(p, 'w'), indent=2, sort_keys=True)
"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"
}

update_tx_phase() {
  tx_write_json "d['phase'] = '$1'"
}

mark_mutation_boundary() {
  tx_write_json "d['mutation_boundary_crossed'] = True"
}

backup_target_db() {
  log "backing up target DB"
  install -d "${DB_BACKUP_DIR}"
  if [[ ! -f "$TARGET_DB" ]]; then
    fail "target DB missing: $TARGET_DB"
  fi
  if ! sqlite3 "$TARGET_DB" "PRAGMA integrity_check;" | grep -q "^ok$"; then
    fail "target DB integrity check failed BEFORE backup"
  fi
  python3 -c "
import sqlite3
src = sqlite3.connect('${TARGET_DB}')
dst = sqlite3.connect('${DB_BACKUP_PATH}')
with dst:
    src.backup(dst)
dst.close()
src.close()
"
  if ! sqlite3 "$DB_BACKUP_PATH" "PRAGMA integrity_check;" | grep -q "^ok$"; then
    fail "DB backup integrity check failed"
  fi
  local backup_sha
  backup_sha="$(sha256 "$DB_BACKUP_PATH")"
  tx_write_json "
d['db_backup_sha256'] = '${backup_sha}'
d['db_backup_integrity'] = 'ok'
"
  log "DB backup: $DB_BACKUP_PATH ($backup_sha)"
}

# stage_candidate_runtime
#
# The new, deterministic staging phase. Delegates entirely to the
# peer_deployer.staging module via the ``stage`` CLI subcommand.
# This means:
#
#   * supervisor's site-packages is copied wholesale
#   * the three SDK wheels are installed with --no-deps
#   * the candidate's runtime identity is verified (SHA + version)
#   * the candidate's package versions match the supervisor closure
#   * PROVENANCE.txt and artifacts/ are written
#   * .complete is touched only after every verify step passes
#
# Live PyPI is never consulted.
stage_candidate_runtime() {
  log "staging candidate runtime at $STAGING_ROOT (per-tx)"
  install -d "${EVIDENCE_DIR}/tx-${TX_ID}"
  cd /tmp
  SYSTEM_PYTHON="$SYSTEM_PYTHON" python3 "${PEER_DEPLOYER_RUNNER}" \
    --target "$TARGET" \
    --supervisor "$SUPERVISOR" \
    --tx-id "$TX_ID" \
    stage \
    2>&1 | tee -a "${EVIDENCE_DIR}/tx-${TX_ID}/staging.log"
}

# verify_candidate_runtime_staged_and_verified
#
# Mandatory pre-mutation gate. Verifies:
#   * .complete marker exists in the staging root
#   * PROVENANCE.txt has the canonical schema
#   * the three SDK wheels are present in artifacts/
#   * the candidate's runtime identity matches the accepted artifact
#   * the candidate's package versions match the supervisor closure
#   * omnigent, omnigent_client, omnigent_ui_sdk import cleanly
#
# Implemented as a Python probe so the assertions match the rest of
# the peer_deployer contract.
verify_candidate_runtime_staged_and_verified() {
  log "verifying candidate runtime at $STAGING_ROOT"
  cd /tmp
  local out
  out="$(SYSTEM_PYTHON="$SYSTEM_PYTHON" python3 - <<PY
import json, os, sys, shutil, subprocess
from pathlib import Path

staging_root = Path("${STAGING_ROOT}")
failures = []
if not staging_root.exists():
    failures.append("missing:staging-root")

# Check .complete
if not (staging_root / ".complete").is_file():
    failures.append("missing:.complete")

# Check PROVENANCE
prov = staging_root / "PROVENANCE.txt"
if not prov.is_file():
    failures.append("missing:PROVENANCE.txt")
else:
    text = prov.read_text()
    for required in ("schema_version=", "sha=", "package_version="):
        if required not in text:
            failures.append(f"missing-in-provenance:{required.rstrip('=')}")

# Check artifacts
artifacts = staging_root / "artifacts"
if not artifacts.is_dir():
    failures.append("missing:artifacts/")
for prefix in ("omnigent-", "omnigent_client-", "omnigent_ui_sdk-"):
    if not any(artifacts.glob(f"{prefix}*.whl")):
        failures.append(f"missing-wheel:{prefix}")

# Check runtime identity via import (not regex)
candidate_python = staging_root / "venv" / "bin" / "python"
if not candidate_python.is_file():
    failures.append("missing-python:venv/bin/python")
else:
    probe = subprocess.run(
        [str(candidate_python), "-c",
         "import json; from omnigent._build_info import COMMIT_SHA;"
         "from importlib.metadata import version as v;"
         "json.dump({'commit_sha': COMMIT_SHA, 'version': v('omnigent')}, __import__('sys').stdout)"],
        capture_output=True, text=True, check=False,
        cwd="/tmp",
        env={"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "PYTHONPATH": "", "PYTHONNOUSERSITE": "1"},
    )
    if probe.returncode != 0:
        failures.append(f"runtime-identity-probe-failed: {probe.stderr.strip()[:200]}")
    else:
        try:
            blob = json.loads(probe.stdout)
        except json.JSONDecodeError:
            failures.append("runtime-identity-probe-not-json")
        else:
            if blob.get("commit_sha") != "${ACCEPTED_SHA}":
                failures.append(f"runtime-sha-mismatch: got {blob.get('commit_sha')!r}")
            if blob.get("version") != "${ACCEPTED_VERSION}":
                failures.append(f"runtime-version-mismatch: got {blob.get('version')!r}")

    # Check that critical imports work
    import_check = subprocess.run(
        [str(candidate_python), "-c",
         "import omnigent, omnigent_client, omnigent_ui_sdk;"
         "import omnigent.db;"
         "import fastapi, opentelemetry;"
         "import opentelemetry.instrumentation.fastapi"],
        capture_output=True, text=True, check=False,
        cwd="/tmp",
        env={"PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
             "PYTHONPATH": "", "PYTHONNOUSERSITE": "1"},
    )
    if import_check.returncode != 0:
        failures.append(f"import-check-failed: {import_check.stderr.strip()[:300]}")

print(json.dumps({"staging_root": str(staging_root), "failures": failures}))
PY
)"
  echo "$out" | tee -a "${EVIDENCE_DIR}/tx-${TX_ID}/candidate-verification.log"
  local failures
  failures="$(echo "$out" | python3 -c 'import json, sys; d=json.loads(sys.stdin.read()); print(",".join(d["failures"]) if d["failures"] else "")')"
  if [[ -n "$failures" ]]; then
    fail "candidate verification failed: $failures"
  fi
  log "candidate runtime verified"
}

migrate_target_db() {
  log "running target DB migration"
  cd /tmp
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    "${STAGING_ROOT}/venv/bin/python" -m \
    omnigent.db.migrate --database-url "sqlite:///${TARGET_DB}" 2>&1 | tee -a "${EVIDENCE_DIR}/tx-${TX_ID}/migration.log"
  local new_schema
  new_schema="$(sqlite3 "$TARGET_DB" "SELECT version_num FROM alembic_version;")"
  if [[ "$new_schema" != "$EXPECTED_DB_SCHEMA" ]]; then
    fail "DB migration did not reach expected schema: $new_schema != $EXPECTED_DB_SCHEMA"
  fi
  log "DB migration complete: $new_schema"
}

switch_target_runtime() {
  log "switching target runtime"
  local target_venv="${TARGET_DEPLOY_ROOT}/venv"
  if [[ -L "$target_venv" ]]; then
    local prev_target
    prev_target="$(readlink -f "$target_venv")"
    log "previous runtime was a symlink -> $prev_target"
  elif [[ -d "$target_venv" ]]; then
    # We're promoting to a new release — the existing venv is from
    # the OLD runtime and must be preserved as the rollback target.
    local legacy
    legacy="${TARGET_DEPLOY_ROOT}/venv.legacy-$(date -u +%Y%m%dT%H%M%SZ)"
    log "renaming existing venv to $legacy"
    mv "$target_venv" "$legacy"
    tx_write_json "
if '$legacy' not in d['owned_resources']:
    d['owned_resources'].append('$legacy')
"
  elif [[ -e "$target_venv" ]]; then
    fail "$target_venv is neither a directory nor a symlink"
  fi
  # Atomically swap: move STAGING_ROOT's venv into FINAL_RELEASE,
  # then symlink venv -> FINAL_RELEASE/venv.
  if [[ -e "$FINAL_RELEASE" ]]; then
    fail "final release path already exists: $FINAL_RELEASE"
  fi
  mv "$STAGING_ROOT" "$FINAL_RELEASE"
  rm -f "$STAGING_ROOT"  # safety: shouldn't exist after mv
  local tmp_link="${TARGET_DEPLOY_ROOT}/.venv.tmp"
  ln -sfn "${FINAL_RELEASE}/venv" "$tmp_link"
  mv -T "$tmp_link" "$target_venv"
  log "venv symlink now -> ${FINAL_RELEASE}/venv"
}

write_target_provenance() {
  cp "${FINAL_RELEASE}/PROVENANCE.txt" "${TARGET_DEPLOY_ROOT}/PROVENANCE.txt"
  printf '%s\n' "$ACCEPTED_SHA" > "${TARGET_DEPLOY_ROOT}/DEPLOYED_SHA"
}

start_target_services() {
  log "starting target services"
  systemctl restart "$TARGET_SERVER_UNIT"
  local deadline=$(( $(date +%s) + 90 ))
  while (( $(date +%s) < deadline )); do
    if curl -fsS --max-time 3 "$TARGET_HEALTH_URL" >/dev/null 2>&1; then
      log "target server healthy"
      break
    fi
    sleep 1
  done
  if ! curl -fsS --max-time 3 "$TARGET_HEALTH_URL" >/dev/null 2>&1; then
    fail "target server not healthy after restart"
  fi
  systemctl restart "$TARGET_HOST_UNIT"
  log "target host restarted"
}

verify_target_acceptance() {
  log "verifying target acceptance"
  local info schema
  info="$(curl -fsS --max-time 10 "http://127.0.0.1:4097/v1/info")"
  schema="$(sqlite3 "$TARGET_DB" "SELECT version_num FROM alembic_version;")"
  local actual_version
  actual_version="$(echo "$info" | python3 -c 'import json, sys; print(json.loads(sys.stdin.read())["server_version"])')"
  if [[ "$actual_version" != "$ACCEPTED_VERSION" ]]; then
    fail "target /v1/info server_version mismatch: $actual_version != $ACCEPTED_VERSION"
  fi
  if [[ "$schema" != "$EXPECTED_DB_SCHEMA" ]]; then
    fail "target DB schema mismatch: $schema"
  fi
  log "target acceptance verified: $ACCEPTED_VERSION / $schema"
}

commit_transaction() {
  update_tx_phase "tx_committed"
  log "transaction committed"
}

pause_target_services() {
  log "stopping target services (for rollback)"
  systemctl stop "$TARGET_HOST_UNIT" || true
  systemctl stop "$TARGET_SERVER_UNIT" || true
  sleep 2
}

paired_rollback() {
  local reason="$1"
  log "PAIRED ROLLBACK initiated: $reason"
  tx_write_json "
d['rollback_reason'] = '''$reason'''
d['phase'] = 'rolled_back'
d['rollback_completed'] = True
"

  pause_target_services

  # 1. Restore DB.
  if [[ -f "$DB_BACKUP_PATH" ]] && sqlite3 "$DB_BACKUP_PATH" "PRAGMA integrity_check;" | grep -q "^ok$"; then
    cp "$DB_BACKUP_PATH" "$TARGET_DB"
    chown hermes:hermes "$TARGET_DB"
    chmod 0644 "$TARGET_DB"
    log "DB restored from backup"
  fi

  # 2. Restore old runtime symlink.
  local legacy
  legacy="$(ls -d "${TARGET_DEPLOY_ROOT}/venv.legacy-"* 2>/dev/null | head -1)"
  if [[ -n "$legacy" ]]; then
    rm -f "${TARGET_DEPLOY_ROOT}/venv"
    ln -sfn "$legacy" "${TARGET_DEPLOY_ROOT}/.venv.tmp.rollback"
    mv -T "${TARGET_DEPLOY_ROOT}/.venv.tmp.rollback" "${TARGET_DEPLOY_ROOT}/venv"
    log "runtime symlink restored to $legacy"
  else
    log "no legacy venv found; runtime dir left untouched"
  fi

  # 3. Restore PROVENANCE.txt.
  if [[ -f "$TARGET_DEPLOY_ROOT/venv/PROVENANCE.txt" ]]; then
    cp "$TARGET_DEPLOY_ROOT/venv/PROVENANCE.txt" "$TARGET_DEPLOY_ROOT/PROVENANCE.txt"
  fi

  # 4. Restart target services.
  systemctl restart "$TARGET_SERVER_UNIT"
  systemctl restart "$TARGET_HOST_UNIT"
  log "paired rollback complete"
}

# ─────────────────────────────────────────────────────────────────────
# Main sequence.
# ─────────────────────────────────────────────────────────────────────

assert_privilege
assert_target_distinct_from_supervisor
assert_supervisor_health
assert_supervisor_identity
assert_artifact_hashes

create_transaction_record
update_tx_phase "preflight"
SUPERVISOR_BEFORE=$(mktemp /tmp/peer-promote-supervisor-before.XXXXXX)
snapshot_supervisor_state "$SUPERVISOR_BEFORE"
cp "$SUPERVISOR_BEFORE" "${EVIDENCE_DIR}/tx-${TX_ID}/supervisor-before.txt"

update_tx_phase "db_backup"
backup_target_db

# Per-transaction staging. Different from peer_promote_o1.sh.
update_tx_phase "candidate_staging"
stage_candidate_runtime

# Mandatory preflight gate. Must pass before any mutation.
update_tx_phase "candidate_verified"
verify_candidate_runtime_staged_and_verified

# Past this point we cross the mutation boundary.
mark_mutation_boundary

update_tx_phase "switch"
switch_target_runtime
write_target_provenance

update_tx_phase "service_restart"
pause_target_services

update_tx_phase "db_migration"
migrate_target_db

update_tx_phase "acceptance"
start_target_services
verify_target_acceptance

# Verify supervisor was untouched.
SUPERVISOR_AFTER=$(mktemp /tmp/peer-promote-supervisor-after.XXXXXX)
snapshot_supervisor_state "$SUPERVISOR_AFTER"
cp "$SUPERVISOR_AFTER" "${EVIDENCE_DIR}/tx-${TX_ID}/supervisor-after.txt"
if ! cmp -s "$SUPERVISOR_BEFORE" "$SUPERVISOR_AFTER"; then
  paired_rollback "supervisor state changed during promotion"
  fail "supervisor was touched; rollback attempted"
fi

# Commit the transaction.
commit_transaction
log "PROMOTION COMPLETE: $TARGET now at $ACCEPTED_SHA / $ACCEPTED_VERSION / schema $EXPECTED_DB_SCHEMA"
log "Evidence: $EVIDENCE_DIR/tx-$TX_ID"
log "Transaction record: $TX_DIR/transaction.json"
echo "TARGET=$TARGET SUPERVISOR=$SUPERVISOR STATUS=COMMITTED TX_ID=$TX_ID"
