#!/usr/bin/env bash
# Peer-supervised O1 promotion — host-level deployer.
#
# This script is the host-level counterpart to the peer_deployer
# Python module. It is generated by the O2 supervisor session and
# executed by the host-level operator (root or sudo-capable user)
# OUTSIDE the O2 sandbox.
#
# The script:
#   1. Verifies the exact accepted artifact SHA, version, and wheel hashes.
#   2. Verifies the target != supervisor identity.
#   3. Runs the O2-side preflight checks (service health, artifact identity).
#   4. Creates a transaction record.
#   5. Backs up the target DB.
#   6. Stages the artifact at the target release root.
#   7. Stops the target's services.
#   8. Migrates the target DB.
#   9. Switches the target's runtime symlink.
#  10. Starts the target's server.
#  11. Waits for health.
#  12. Starts/reconnects the target's host.
#  13. Runs focused acceptance.
#  14. Commits the transaction.
#  15. Preserves rollback artifacts.
#
# On any failure, the script performs a paired rollback using the
# transaction record. The rollback is restricted to resources owned
# by the transaction and refuses to touch the active runtime unless
# it is the transaction-created candidate.
#
# The script is intentionally narrow. It cannot upgrade the supervisor.
# It cannot change target/supervisor identity. It cannot deploy any
# artifact other than the exact accepted one.

set -euo pipefail

# ─────────────────────────────────────────────────────────────────────
# Configuration — generated by the O2 supervisor session.
# Edit ONLY the operational variables (TX_ROOT, EVIDENCE_DIR). Do not
# change the runtime identity or the wheel hashes.
# ─────────────────────────────────────────────────────────────────────

TARGET="O1"
SUPERVISOR="O2"

ACCEPTED_SHA="541c9a3180b81bfb2fc450b3ef5f8648691b359d"
ACCEPTED_VERSION="0.9.0.dev0"
EXPECTED_MAIN_WHEEL_SHA256="f49fb3f973c1d98be03eaede76e9c7e86acb91064b06494afdf8f7345524a5e9"
EXPECTED_SDK_CLIENT_WHEEL_SHA256="555a6286477bd528005478571b24cd2fda5c9da505f0957d606b6182614f9605"
EXPECTED_SDK_UI_WHEEL_SHA256="e2141bc6af3bee42a85cad1ff48d008d20439ee34cb52956cda1b7fdff1d45a9"
EXPECTED_DB_SCHEMA="f7a8b9c0d1e2"

# Layout.
TARGET_DEPLOY_ROOT="/opt/omnigent"
TARGET_HOME="/var/lib/omnigent"
SUPERVISOR_DEPLOY_ROOT="/opt/omnigent-production"
SUPERVISOR_HOME="/var/lib/omnigent-production"

SOURCE_RELEASE="${SUPERVISOR_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}"
SOURCE_ARTIFACTS="${SOURCE_RELEASE}/artifacts"
SOURCE_MAIN_WHEEL="${SOURCE_ARTIFACTS}/omnigent-${ACCEPTED_VERSION}-py3-none-any.whl"
SOURCE_SDK_CLIENT_WHEEL="${SOURCE_ARTIFACTS}/omnigent_client-${ACCEPTED_VERSION}-py3-none-any.whl"
SOURCE_SDK_UI_WHEEL="${SOURCE_ARTIFACTS}/omnigent_ui_sdk-${ACCEPTED_VERSION}-py3-none-any.whl"

TARGET_SERVER_UNIT="omnigent.service"
TARGET_HOST_UNIT="omnigent-host.service"
SUPERVISOR_SERVER_UNIT="omnigent-production.service"
SUPERVISOR_HOST_UNIT="omnigent-production-host.service"
TARGET_HEALTH_URL="http://127.0.0.1:4097/health"
SUPERVISOR_HEALTH_URL="http://127.0.0.1:4197/health"

# Transaction state.
TX_ROOT="${OMNIGENT_CONTROL_ROOM_TX_ROOT:-/var/lib/omnigent-control-room/transactions}"
EVIDENCE_DIR="${OMNIGENT_CONTROL_ROOM_EVIDENCE_DIR:-/var/lib/omnigent-production/upstream-0.9-candidate-20260808T100458Z/16-peer-deployer-hardening-and-o1-promotion}"
TX_ID="promotion-$(date -u +%Y%m%dT%H%M%SZ)-$(head -c 4 /dev/urandom | xxd -p)"
TX_DIR="${TX_ROOT}/${TX_ID}"
TARGET_DB="${TARGET_HOME}/chat.db"
DB_BACKUP_DIR="${EVIDENCE_DIR}/tx-${TX_ID}"
DB_BACKUP_PATH="${DB_BACKUP_DIR}/chat.db"

# Python helper location.
PEER_DEPLOYER_DIR="/home/hermes/workspace/worktrees/peer-deployer-hardening/deploy/scripts"
SUN_PROD_REPO="/home/hermes/workspace/repos/omnigent-2-production"

# ─────────────────────────────────────────────────────────────────────
# Helpers.
# ─────────────────────────────────────────────────────────────────────

log()  { printf '[peer-promote-o1 %s] %s\n' "$TX_ID" "$*" >&2; }
fail() { printf '[peer-promote-o1 %s] FAIL: %s\n' "$TX_ID" "$*" >&2; exit 1; }

sha256() { sha256sum "$1" | awk '{print $1}'; }

# service_state_active <unit>
# Returns 0 iff the unit is in the "active" state. Uses the
# vetted peer-deployer helper to avoid the broken
# `is-active | grep -q` pattern under pipefail.
service_state_active() {
  local unit="$1"
  local state
  state="$(systemctl is-active "$unit" 2>/dev/null || true)"
  state="${state,,}"
  state="${state//[[:space:]]/}"
  [[ "$state" == "active" ]]
}

assert_privilege() {
  if [[ $EUID -ne 0 ]]; then
    fail "must run as root (or under sudo -E)"
  fi
}

assert_supervisor_health() {
  install -d "${EVIDENCE_DIR}"
  install -d "${TX_DIR}"
  log "verifying supervisor health"
  if ! systemctl cat "$SUPERVISOR_SERVER_UNIT" >/dev/null 2>&1; then
    fail "supervisor service unit not installed: $SUPERVISOR_SERVER_UNIT"
  fi
  if ! systemctl cat "$SUPERVISOR_HOST_UNIT" >/dev/null 2>&1; then
    fail "supervisor host unit not installed: $SUPERVISOR_HOST_UNIT"
  fi
  if ! service_state_active "$SUPERVISOR_SERVER_UNIT"; then
    fail "supervisor server is not active: $SUPERVISOR_SERVER_UNIT"
  fi
  if ! service_state_active "$SUPERVISOR_HOST_UNIT"; then
    fail "supervisor host is not active: $SUPERVISOR_HOST_UNIT"
  fi
  if ! curl -fsS --max-time 5 "$SUPERVISOR_HEALTH_URL" >/dev/null 2>&1; then
    fail "supervisor /health not OK: $SUPERVISOR_HEALTH_URL"
  fi
}

assert_supervisor_identity() {
  local actual_sha actual_version
  actual_sha="$(cat "${SUPERVISOR_DEPLOY_ROOT}/current/venv/lib/python3.12/site-packages/omnigent/_build_info.py" | grep -E "COMMIT_SHA" | head -1 | sed -E "s/.*COMMIT_SHA[:\s]*['\"]?([0-9a-f]{40}).*/\1/")"
  actual_version="$("${SUPERVISOR_DEPLOY_ROOT}/current/venv/bin/python" -c "from omnigent.version import VERSION; print(VERSION)" 2>/dev/null)"
  if [[ "$actual_sha" != "$ACCEPTED_SHA" ]]; then
    fail "supervisor installed SHA $actual_sha != accepted $ACCEPTED_SHA"
  fi
  if [[ "$actual_version" != "$ACCEPTED_VERSION" ]]; then
    fail "supervisor installed version $actual_version != accepted $ACCEPTED_VERSION"
  fi
  log "supervisor identity verified: $actual_sha / $actual_version"
}

assert_artifact_hashes() {
  if [[ ! -d "$SOURCE_RELEASE" ]]; then
    fail "accepted release dir missing: $SOURCE_RELEASE"
  fi
  if [[ ! -f "$SOURCE_MAIN_WHEEL" ]]; then
    fail "accepted main wheel missing: $SOURCE_MAIN_WHEEL"
  fi
  if [[ ! -f "$SOURCE_SDK_CLIENT_WHEEL" ]]; then
    fail "accepted SDK client wheel missing: $SOURCE_SDK_CLIENT_WHEEL"
  fi
  if [[ ! -f "$SOURCE_SDK_UI_WHEEL" ]]; then
    fail "accepted SDK UI wheel missing: $SOURCE_SDK_UI_WHEEL"
  fi
  local actual
  actual="$(sha256 "$SOURCE_MAIN_WHEEL")"
  [[ "$actual" == "$EXPECTED_MAIN_WHEEL_SHA256" ]] || fail "main wheel SHA mismatch: $actual"
  actual="$(sha256 "$SOURCE_SDK_CLIENT_WHEEL")"
  [[ "$actual" == "$EXPECTED_SDK_CLIENT_WHEEL_SHA256" ]] || fail "SDK client wheel SHA mismatch: $actual"
  actual="$(sha256 "$SOURCE_SDK_UI_WHEEL")"
  [[ "$actual" == "$EXPECTED_SDK_UI_WHEEL_SHA256" ]] || fail "SDK UI wheel SHA mismatch: $actual"
  log "all three wheel SHA-256 verified"
}

assert_target_distinct_from_supervisor() {
  if [[ "$TARGET" == "$SUPERVISOR" ]]; then
    fail "REFUSED: target == supervisor == $TARGET"
  fi
  if [[ "$TARGET_DEPLOY_ROOT" == "$SUPERVISOR_DEPLOY_ROOT" ]]; then
    fail "REFUSED: target and supervisor share deploy root"
  fi
  if [[ "$TARGET_HOME" == "$SUPERVISOR_HOME" ]]; then
    fail "REFUSED: target and supervisor share home"
  fi
  if [[ "$TARGET_SERVER_UNIT" == "$SUPERVISOR_SERVER_UNIT" ]]; then
    fail "REFUSED: target and supervisor share service unit"
  fi
  log "target ($TARGET) != supervisor ($SUPERVISOR)"
}

snapshot_supervisor_state() {
  local out="$1"
  : > "$out"
  for unit in "$SUPERVISOR_SERVER_UNIT" "$SUPERVISOR_HOST_UNIT"; do
    systemctl show "$unit" -p MainPID -p NRestarts -p ActiveEnterTimestampMonotonic \
      -p ActiveEnterTimestamp -p ActiveState >> "$out" 2>&1 || return 1
  done
}

create_transaction_record() {
  local provenance
  provenance="${SOURCE_RELEASE}/PROVENANCE.txt"
  if [[ ! -f "$provenance" ]]; then
    fail "PROVENANCE.txt missing: $provenance"
  fi
  cat > "${TX_DIR}/transaction.json" <<JSON
{
  "tx_id": "${TX_ID}",
  "target": "${TARGET}",
  "supervisor": "${SUPERVISOR}",
  "target_artifact_sha": "${ACCEPTED_SHA}",
  "target_artifact_version": "${ACCEPTED_VERSION}",
  "main_wheel_sha256": "${EXPECTED_MAIN_WHEEL_SHA256}",
  "sdk_client_wheel_sha256": "${EXPECTED_SDK_CLIENT_WHEEL_SHA256}",
  "sdk_ui_wheel_sha256": "${EXPECTED_SDK_UI_WHEEL_SHA256}",
  "created_at_unix": $(date +%s),
  "phase": "init",
  "mutation_boundary_crossed": false,
  "old_runtime_path": "${TARGET_DEPLOY_ROOT}/venv",
  "old_runtime_sha": "$(cat "${TARGET_DEPLOY_ROOT}/venv/lib/python3.12/site-packages/omnigent/_build_info.py" 2>/dev/null | grep -E "COMMIT_SHA" | head -1 | sed -E "s/.*COMMIT_SHA[:\s]*['\"]?([0-9a-f]{40}).*/\1/")",
  "old_runtime_version": "0.8.1",
  "new_runtime_path": "${TARGET_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}",
  "new_runtime_sha": "${ACCEPTED_SHA}",
  "new_runtime_version": "${ACCEPTED_VERSION}",
  "db_backup_path": "${DB_BACKUP_PATH}",
  "db_backup_sha256": "",
  "db_backup_integrity": "",
  "old_db_schema": "c4d5e6f7a8b9",
  "target_db_schema": "${EXPECTED_DB_SCHEMA}",
  "owned_resources": [],
  "log_path": "${EVIDENCE_DIR}/tx-${TX_ID}/promotion.log",
  "rollback_reason": "",
  "rollback_completed": false
}
JSON
  install -d "${EVIDENCE_DIR}/tx-${TX_ID}"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"
}

update_tx_phase() {
  local phase="$1"
  python3 -c "
import json, sys
p = '${TX_DIR}/transaction.json'
d = json.load(open(p))
d['phase'] = '${phase}'
json.dump(d, open(p, 'w'), indent=2, sort_keys=True)
"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"
}

mark_mutation_boundary() {
  python3 -c "
import json, sys
p = '${TX_DIR}/transaction.json'
d = json.load(open(p))
d['mutation_boundary_crossed'] = True
json.dump(d, open(p, 'w'), indent=2, sort_keys=True)
"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"
}

register_owned() {
  local path="$1"
  python3 -c "
import json, sys
p = '${TX_DIR}/transaction.json'
d = json.load(open(p))
if '$path' not in d['owned_resources']:
    d['owned_resources'].append('$path')
json.dump(d, open(p, 'w'), indent=2, sort_keys=True)
"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"
}

backup_target_db() {
  log "backing up target DB"
  install -d "${DB_BACKUP_DIR}"
  if [[ ! -f "$TARGET_DB" ]]; then
    fail "target DB missing: $TARGET_DB"
  fi
  if ! sqlite3 "$TARGET_DB" "PRAGMA integrity_check;" | grep -q "^ok$"; then
    fail "target DB integrity check failed BEFORE backup"
  fi
  python3 -c "
import sqlite3, shutil
src = sqlite3.connect('${TARGET_DB}')
dst = sqlite3.connect('${DB_BACKUP_PATH}')
with dst:
    src.backup(dst)
dst.close()
src.close()
"
  if ! sqlite3 "$DB_BACKUP_PATH" "PRAGMA integrity_check;" | grep -q "^ok$"; then
    fail "DB backup integrity check failed"
  fi
  local backup_sha
  backup_sha="$(sha256 "$DB_BACKUP_PATH")"
  python3 -c "
import json
p = '${TX_DIR}/transaction.json'
d = json.load(open(p))
d['db_backup_sha256'] = '${backup_sha}'
d['db_backup_integrity'] = 'ok'
json.dump(d, open(p, 'w'), indent=2, sort_keys=True)
"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"
  log "DB backup: $DB_BACKUP_PATH ($backup_sha)"
}

stage_target_release() {
  log "staging target release"
  local target_release="${TARGET_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}"
  if [[ -e "$target_release" ]]; then
    fail "target release already exists: $target_release (refusing to overwrite)"
  fi
  install -d "${target_release}/artifacts"
  cp "$SOURCE_MAIN_WHEEL" "${target_release}/artifacts/"
  cp "$SOURCE_SDK_CLIENT_WHEEL" "${target_release}/artifacts/"
  cp "$SOURCE_SDK_UI_WHEEL" "${target_release}/artifacts/"
  cp "${SOURCE_RELEASE}/PROVENANCE.txt" "${target_release}/PROVENANCE.txt"
  # Build the venv.
  python3 -m venv "${target_release}/venv"
  "${target_release}/venv/bin/pip" install --no-cache-dir \
    "${target_release}/artifacts/omnigent-${ACCEPTED_VERSION}-py3-none-any.whl[all]" \
    "${target_release}/artifacts/omnigent_client-${ACCEPTED_VERSION}-py3-none-any.whl" \
    "${target_release}/artifacts/omnigent_ui_sdk-${ACCEPTED_VERSION}-py3-none-any.whl"
  if [[ ! -f "${target_release}/.complete" ]]; then
    touch "${target_release}/.complete"
  fi
  chmod -R a-w "${target_release}/PROVENANCE.txt" "${target_release}/artifacts"
  register_owned "$target_release"
  log "staged: $target_release"
}

migrate_target_db() {
  log "running target DB migration"
  cd /tmp
  PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" \
    "${TARGET_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}/venv/bin/python" -m \
    omnigent.db.migrate --database-url "sqlite:///${TARGET_DB}" 2>&1 | tee -a "${EVIDENCE_DIR}/tx-${TX_ID}/migration.log"
  local new_schema
  new_schema="$(sqlite3 "$TARGET_DB" "SELECT version_num FROM alembic_version;")"
  if [[ "$new_schema" != "$EXPECTED_DB_SCHEMA" ]]; then
    fail "DB migration did not reach expected schema: $new_schema != $EXPECTED_DB_SCHEMA"
  fi
  log "DB migration complete: $new_schema"
}

switch_target_runtime() {
  log "switching target runtime"
  local target_venv="${TARGET_DEPLOY_ROOT}/venv"
  if [[ -L "$target_venv" ]]; then
    local prev_target
    prev_target="$(readlink -f "$target_venv")"
    log "previous runtime was a symlink -> $prev_target"
  elif [[ -d "$target_venv" ]]; then
    # We're promoting to a new release — the existing venv is from
    # the OLD runtime and must be preserved as the rollback target.
    local legacy
    legacy="${TARGET_DEPLOY_ROOT}/venv.legacy-$(date -u +%Y%m%dT%H%M%SZ)"
    log "renaming existing venv to $legacy"
    mv "$target_venv" "$legacy"
    register_owned "$legacy"
  elif [[ -e "$target_venv" ]]; then
    fail "$target_venv is neither a directory nor a symlink"
  fi
  local tmp_link="${TARGET_DEPLOY_ROOT}/.venv.tmp"
  ln -sfn "${TARGET_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}/venv" "$tmp_link"
  mv -T "$tmp_link" "$target_venv"
  log "venv symlink now -> ${TARGET_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}/venv"
}

write_target_provenance() {
  cp "${TARGET_DEPLOY_ROOT}/releases/${ACCEPTED_SHA}/PROVENANCE.txt" "${TARGET_DEPLOY_ROOT}/PROVENANCE.txt"
  printf '%s\n' "$ACCEPTED_SHA" > "${TARGET_DEPLOY_ROOT}/DEPLOYED_SHA"
}

start_target_services() {
  log "starting target services"
  systemctl restart "$TARGET_SERVER_UNIT"
  # Wait for health.
  local deadline=$(( $(date +%s) + 90 ))
  while (( $(date +%s) < deadline )); do
    if curl -fsS --max-time 3 "$TARGET_HEALTH_URL" >/dev/null 2>&1; then
      log "target server healthy"
      break
    fi
    sleep 1
  done
  if ! curl -fsS --max-time 3 "$TARGET_HEALTH_URL" >/dev/null 2>&1; then
    fail "target server not healthy after restart"
  fi
  systemctl restart "$TARGET_HOST_UNIT"
  log "target host restarted"
}

verify_target_acceptance() {
  log "verifying target acceptance"
  local info schema
  info="$(curl -fsS --max-time 10 "http://127.0.0.1:4097/v1/info")"
  schema="$(sqlite3 "$TARGET_DB" "SELECT version_num FROM alembic_version;")"
  python3 -c "
import json, sys
info = json.loads('''$info''')
assert info['server_version'] == '${ACCEPTED_VERSION}', f'got {info[\"server_version\"]!r}'
" || fail "target /v1/info server_version mismatch"
  if [[ "$schema" != "$EXPECTED_DB_SCHEMA" ]]; then
    fail "target DB schema mismatch: $schema"
  fi
  log "target acceptance verified: $ACCEPTED_VERSION / $schema"
}

commit_transaction() {
  update_tx_phase "tx_committed"
  log "transaction committed"
}

pause_target_services() {
  log "stopping target services (for rollback)"
  systemctl stop "$TARGET_HOST_UNIT" || true
  systemctl stop "$TARGET_SERVER_UNIT" || true
  sleep 2
}

refuse_unowned_rollback() {
  local path="$1"
  python3 -c "
import json, os, sys
p = '${TX_DIR}/transaction.json'
d = json.load(open(p))
real = os.path.realpath('$path')
for owned in d['owned_resources']:
    if os.path.realpath(owned) == real:
        sys.exit(0)
sys.stderr.write('REFUSED: $path is not owned by transaction ${TX_ID}\n')
sys.exit(1)
" || fail "rollback refused: $path is not owned"
}

paired_rollback() {
  local reason="$1"
  log "PAIRED ROLLBACK initiated: $reason"
  python3 -c "
import json
p = '${TX_DIR}/transaction.json'
d = json.load(open(p))
d['rollback_reason'] = '''$reason'''
d['phase'] = 'rolled_back'
d['rollback_completed'] = True
json.dump(d, open(p, 'w'), indent=2, sort_keys=True)
"
  cp "${TX_DIR}/transaction.json" "${EVIDENCE_DIR}/tx-${TX_ID}/transaction.json"

  pause_target_services

  # 1. Restore DB.
  if [[ -f "$DB_BACKUP_PATH" ]] && sqlite3 "$DB_BACKUP_PATH" "PRAGMA integrity_check;" | grep -q "^ok$"; then
    cp "$DB_BACKUP_PATH" "$TARGET_DB"
    chown hermes:hermes "$TARGET_DB"
    chmod 0644 "$TARGET_DB"
    log "DB restored from backup"
  fi

  # 2. Restore old runtime symlink.
  # The legacy venv was created in switch_target_runtime and is in
  # owned_resources. We do not delete it; we re-symlink to it.
  local legacy
  legacy="$(ls -d "${TARGET_DEPLOY_ROOT}/venv.legacy-"* 2>/dev/null | head -1)"
  if [[ -n "$legacy" ]]; then
    rm -f "${TARGET_DEPLOY_ROOT}/venv"
    ln -sfn "$legacy" "${TARGET_DEPLOY_ROOT}/.venv.tmp.rollback"
    mv -T "${TARGET_DEPLOY_ROOT}/.venv.tmp.rollback" "${TARGET_DEPLOY_ROOT}/venv"
    log "runtime symlink restored to $legacy"
  else
    log "no legacy venv found; runtime dir left untouched"
  fi

  # 3. Restore PROVENANCE.txt.
  if [[ -f "$TARGET_DEPLOY_ROOT/venv/PROVENANCE.txt" ]]; then
    cp "$TARGET_DEPLOY_ROOT/venv/PROVENANCE.txt" "$TARGET_DEPLOY_ROOT/PROVENANCE.txt"
  fi

  # 4. Restart target services.
  systemctl restart "$TARGET_SERVER_UNIT"
  systemctl restart "$TARGET_HOST_UNIT"
  log "paired rollback complete"
}

# ─────────────────────────────────────────────────────────────────────
# Main sequence.
# ─────────────────────────────────────────────────────────────────────

assert_privilege
assert_target_distinct_from_supervisor
assert_supervisor_health
assert_supervisor_identity
assert_artifact_hashes

create_transaction_record
update_tx_phase "preflight"
SUPERVISOR_BEFORE=$(mktemp /tmp/peer-promote-supervisor-before.XXXXXX)
snapshot_supervisor_state "$SUPERVISOR_BEFORE"
register_owned "$SUPERVISOR_BEFORE"
cp "$SUPERVISOR_BEFORE" "${EVIDENCE_DIR}/tx-${TX_ID}/supervisor-before.txt"

update_tx_phase "db_backup"
backup_target_db

update_tx_phase "candidate_staging"
stage_target_release

# At this point we cross the mutation boundary.
mark_mutation_boundary

update_tx_phase "switch"
switch_target_runtime
write_target_provenance

update_tx_phase "service_restart"
pause_target_services

update_tx_phase "db_migration"
migrate_target_db

update_tx_phase "acceptance"
start_target_services
verify_target_acceptance

# Verify supervisor was untouched.
SUPERVISOR_AFTER=$(mktemp /tmp/peer-promote-supervisor-after.XXXXXX)
snapshot_supervisor_state "$SUPERVISOR_AFTER"
cp "$SUPERVISOR_AFTER" "${EVIDENCE_DIR}/tx-${TX_ID}/supervisor-after.txt"
if ! cmp -s "$SUPERVISOR_BEFORE" "$SUPERVISOR_AFTER"; then
  paired_rollback "supervisor state changed during promotion"
  fail "supervisor was touched; rollback attempted"
fi

# Commit the transaction.
commit_transaction
log "PROMOTION COMPLETE: $TARGET now at $ACCEPTED_SHA / $ACCEPTED_VERSION / schema $EXPECTED_DB_SCHEMA"
log "Evidence: $EVIDENCE_DIR/tx-$TX_ID"
log "Transaction record: $TX_DIR/transaction.json"
echo "TARGET=$TARGET SUPERVISOR=$SUPERVISOR STATUS=COMMITTED TX_ID=$TX_ID"
