"""Tests for the narrow request interface (issue #38 §2).

The interface is the only entry point an agent / operator uses to
file an update request. It must accept only the strict schema and
must reject arbitrary commands, paths, or environment overrides.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from omnigent.updater import layout
from omnigent.updater.request_tool import (
    RequestInterfaceError,
    invoke_sys_update_request,
    record_request,
    sys_update_request_payload,
)
from omnigent.updater.store import UpdaterStore


def _payload(
    target: str = "0" * 40,
    expected: str = "0" * 40,
    operator: str = "tester",
    **extra: object,
) -> dict[str, object]:
    body: dict[str, object] = {
        "target_sha": target,
        "expected_current_sha": expected,
        "requested_by": f"operator:{operator}",
        "authorization": {"kind": "operator", "operator": operator},
    }
    body.update(extra)
    return body


def test_record_request_accepts_valid_payload(state_root: Path) -> None:
    """A minimal valid payload returns a durable request id."""
    outcome = record_request(_payload())
    assert outcome.request_id
    path = layout.requests_dir() / f"{outcome.request_id}.json"
    assert path.is_file()


def test_record_request_rejects_unknown_fields(state_root: Path) -> None:
    """Any extra field is rejected with ``RequestInterfaceError``."""
    payload = _payload()
    payload["shell_command"] = "rm -rf /"
    with pytest.raises(RequestInterfaceError) as exc:
        record_request(payload)
    assert "unknown fields" in str(exc.value).lower()


def test_record_request_rejects_path_field(state_root: Path) -> None:
    """An attempted path injection is rejected."""
    payload = _payload(path="/etc/passwd")
    with pytest.raises(RequestInterfaceError):
        record_request(payload)


def test_record_request_rejects_environment_override(state_root: Path) -> None:
    """A payload that smuggles an env override is rejected."""
    payload = _payload(env={"OMNIGENT_DEPLOY_ROOT": "/tmp/evil"})
    with pytest.raises(RequestInterfaceError):
        record_request(payload)


def test_record_request_rejects_remote_field(state_root: Path) -> None:
    """A payload that names a remote is rejected."""
    payload = _payload(remote="git@evil.example:owner/evil.git")
    with pytest.raises(RequestInterfaceError):
        record_request(payload)


def test_record_request_rejects_malformed_target_sha(state_root: Path) -> None:
    with pytest.raises(RequestInterfaceError):
        record_request(_payload(target="not-a-sha"))


def test_record_request_rejects_uppercase_target_sha(state_root: Path) -> None:
    with pytest.raises(RequestInterfaceError):
        record_request(_payload(target="0123456789ABCDEF0123456789ABCDEF01234567"))


def test_record_request_requires_authorization(state_root: Path) -> None:
    payload = _payload()
    del payload["authorization"]
    with pytest.raises(RequestInterfaceError):
        record_request(payload)


def test_record_request_requires_operator_name_for_kind_operator(
    state_root: Path,
) -> None:
    payload = _payload()
    payload["authorization"] = {"kind": "operator"}
    with pytest.raises(RequestInterfaceError):
        record_request(payload)


def test_record_request_accepts_verity_kind(state_root: Path) -> None:
    """``verity``-kind requests do not require an operator name."""
    payload = _payload()
    payload["requested_by"] = "verity"
    payload["authorization"] = {"kind": "verity"}
    outcome = record_request(payload)
    assert outcome.request_id


def test_record_request_rejects_non_dict_payload(state_root: Path) -> None:
    with pytest.raises(RequestInterfaceError):
        record_request("not a dict")  # type: ignore[arg-type]


def test_record_request_returns_durable_id(state_root: Path) -> None:
    """The returned id is durable on disk under ``requests/``."""
    outcome = record_request(_payload())
    on_disk = layout.requests_dir() / f"{outcome.request_id}.json"
    assert on_disk.is_file()


def test_record_request_retries_on_collision(state_root: Path) -> None:
    """``record_request`` retries a fresh id when the first collides."""
    store = UpdaterStore(state_root=state_root)
    payload = _payload()
    # Pre-create a request file so the next id collides with the
    # first id generated by record_request.
    from omnigent.updater.protocol import (
        Authorization,
        RequestRecord,
        new_request_id,
    )

    collision_id = new_request_id()
    record = RequestRecord(
        request_id=collision_id,
        target_sha="0" * 40,
        expected_current_sha="0" * 40,
        origin_session_id=None,
        origin_conversation_id=None,
        requested_by="operator:tester",
        created_at="2026-01-01T00:00:00Z",
        authorization=Authorization(kind="operator", operator="tester"),
    )
    store.create_request(record)
    # Patch the id generator temporarily so the first attempt
    # collides. After the retry succeeds, the new id is on disk.
    import omnigent.updater.request_tool as rt

    real = rt.new_request_id
    calls = {"n": 0}

    def fake() -> str:
        calls["n"] += 1
        if calls["n"] == 1:
            return collision_id
        return real()

    rt.new_request_id = fake  # type: ignore[assignment]
    try:
        outcome = record_request(payload)
    finally:
        rt.new_request_id = real  # type: ignore[assignment]
    assert outcome.request_id != collision_id


def test_sys_update_request_payload_is_narrow() -> None:
    """The ``sys_update_request`` adapter only produces the narrow schema."""
    payload = sys_update_request_payload(
        target_sha="0" * 40,
        expected_current_sha="0" * 40,
        origin_conversation_id="conv_abc",
    )
    assert set(payload.keys()) == {
        "target_sha",
        "expected_current_sha",
        "requested_by",
        "authorization",
        "origin_conversation_id",
    }
    assert payload["requested_by"] == "verity"
    assert payload["authorization"] == {"kind": "verity"}


def test_invoke_sys_update_request_returns_request_id(state_root: Path) -> None:
    result = invoke_sys_update_request(
        target_sha="0" * 40,
        expected_current_sha="0" * 40,
        origin_conversation_id="conv_abc",
    )
    assert result["request_id"]
    assert result["request_path"].endswith(f"{result['request_id']}.json")
    on_disk = layout.requests_dir() / f"{result['request_id']}.json"
    assert on_disk.is_file()
