#!/usr/bin/env bash
# Sudoers-gated wrapper around the systemd drop-in writer.
#
# This wrapper is what ``scripts/promote_release.sh`` and
# ``scripts/rollback_release.sh`` invoke under ``sudo`` to write the
# per-release drop-in for the omnigent-eval-web and omnigent-eval-host
# systemd units. The wrapper enforces five invariants the promotion /
# rollback scripts cannot enforce from a regular shell:
#
#   1. The service name must be one of an explicit allow-list
#      (web | host). No other service can be reconfigured by this
#      wrapper, so a malicious or buggy caller cannot use it to
#      rewrite drop-ins for unrelated systemd units.
#   2. The release directory must live under the approved root
#      ``/home/hermes/workspace/deployments/omnigent/releases/``.
#      This blocks a caller from pointing the unit at a different
#      tree (e.g. a developer checkout).
#   3. The SHA argument must not contain shell metacharacters. The
#      SHA is interpolated into a drop-in file under a fixed
#      filename pattern, so a metachar inside SHA could escape
#      the file write.
#   4. The action must be one of ``write`` or ``disable``. The
#      ``write`` action creates / replaces the drop-in; ``disable``
#      moves any sibling ``10-release-<other-sha>.conf`` to
#      ``.disabled`` so the new drop-in wins precedence.
#   5. The drop-in body is composed in pure shell (no
#      ``python -c`` against the release's interpreter). The
#      release's ``omni`` / ``python`` scripts are generated by
#      ``uv pip install`` with shebangs pointing at the build-time
#      staging directory; if the promotion script relied on those
#      scripts at drop-in-write time, the resulting drop-in would
#      only work for the build that produced it. By composing the
#      drop-in directly in bash we avoid this entirely: the only
#      release paths referenced from the drop-in are passed by the
#      caller (and rewritten to the canonical post-rename path by
#      ``promote_release.sh``) and validated against the approved
#      release root before any drop-in is written.
#
# Usage:
#   write-dropin.sh write <service> <sha> <release-dir>
#   write-dropin.sh disable <service> <sha> <release-dir>
#
# The service argument selects which unit to reconfigure; ``web``
# writes / disables drop-ins under
# ``/etc/systemd/system/omnigent-eval-web.service.d/`` and ``host``
# does the same under
# ``/etc/systemd/system/omnigent-eval-host.service.d/``. Both
# services are pinned to the same release — this wrapper is the
# single point of truth for both drop-in trees.

set -euo pipefail

if [[ $# -lt 4 ]]; then
  echo "usage: $0 <write|disable> <web|host> <sha> <release-dir>" >&2
  exit 2
fi

ACTION="$1"
SERVICE_KIND="$2"
SHA="$3"
RELEASE_DIR="$4"

# 1. Allow-list the action.
case "$ACTION" in
    write|disable) ;;
    *) echo "unknown action: $ACTION" >&2; exit 2 ;;
esac

# 2. Allow-list the service.
case "$SERVICE_KIND" in
    web|host) ;;
    *) echo "unknown service kind: $SERVICE_KIND (expected web|host)" >&2; exit 2 ;;
esac

# 3. Refuse any SHA arg that contains shell metacharacters. The
# SHA ends up in a drop-in filename, so a metachar inside SHA
# could escape the write or surprise the kernel.
case "$SHA" in
    *[\`\"\;\\\&\$\|\<\>\(\)\{\}\[\]\\\ ]*) echo "bad SHA arg" >&2; exit 2 ;;
esac

# 4. Pin the release directory to the approved root. Anything else
# is rejected before any drop-in is written.
case "$RELEASE_DIR" in
    /home/hermes/workspace/deployments/omnigent/releases/*) ;;
    *) echo "release dir outside approved root: $RELEASE_DIR" >&2; exit 2 ;;
esac

# 5. Pin the release venv too — the drop-in's ExecStartPre runs the
# release's own Python interpreter as a provenance gate. Refuse to
# write a drop-in for a release whose venv is missing or whose
# Python shebang does not resolve. The check is best-effort: a
# later promotion / rollback will surface any structural drift.
case "$RELEASE_DIR" in
    */.staging-*) echo "release dir is a staging directory: $RELEASE_DIR" >&2; exit 2 ;;
esac
[[ -x "$RELEASE_DIR/.venv/bin/python" ]] || {
    echo "release venv python missing: $RELEASE_DIR/.venv/bin/python" >&2
    exit 2
}

case "$SERVICE_KIND" in
    web)
        DROPIN_DIR="/etc/systemd/system/omnigent-eval-web.service.d"
        UNIT_DESCRIPTION="Pin omnigent-eval-web at release"
        ;;
    host)
        DROPIN_DIR="/etc/systemd/system/omnigent-eval-host.service.d"
        UNIT_DESCRIPTION="Pin omnigent-eval-host at release"
        ;;
esac

DROPIN_FILE="$DROPIN_DIR/10-release-${SHA:0:12}.conf"

case "$ACTION" in
    disable)
        # Move any sibling ``10-release-<other-sha>.conf`` to
        # ``.disabled`` so the new drop-in wins precedence. We
        # rely on the caller having just written a drop-in for
        # SHA, so any other ``10-release-*.conf`` is stale.
        shopt -s nullglob
        moved=()
        for f in "$DROPIN_DIR"/10-release-*.conf; do
            base=$(basename "$f")
            if [[ "$base" != "10-release-${SHA:0:12}.conf" ]]; then
                mv "$f" "$f.disabled"
                moved+=("$f.disabled")
            fi
        done
        shopt -u nullglob
        if [[ "${#moved[@]}" -gt 0 ]]; then
            printf 'disabled: %s\n' "${moved[@]}"
        fi
        exit 0
        ;;
esac

# Compose the drop-in body. The body deliberately inlines both
# ExecStartPre and ExecStart with the resolved release path —
# systemd does not expand ``%E`` / env-var references inside
# ``ExecStart`` (only inside ``EnvironmentFile=-`` and a few
# directives), so indirection would let a future edit
# mis-target the wrong release.
#
# The web drop-in runs ``omnigent server`` via the release's own
# Python interpreter (``-P`` disables unsafe sys.path prepending
# so an attacker-controlled cwd cannot shadow site-packages).
#
# The host drop-in invokes the host daemon via ``python -m
# omnigent host`` rather than the release's ``.venv/bin/omni``
# console script. ``omni`` is a generated shim whose shebang
# references the build-time staging directory; rewriting that
# shebang is fragile (uv regenerates it on every reinstall). The
# ``python -m omnigent host`` form always works because the
# release venv's Python is pinned and ``omnigent`` is installed
# non-editable inside site-packages — and the form is identical
# across releases, so a single drop-in template survives every
# rollback to an older release that lacked ``host_service_spec``.
#
# The host drop-in's ``ExecStopPost`` uses the same
# ``python -m omnigent host stop`` form so a clean ``systemctl
# stop`` invokes the host daemon's stop handler via the same
# pinned interpreter. systemd only runs ``ExecStopPost`` on
# success (or for non-zero results we explicitly ``-`` prefix
# so the unit does not fail), so a missing or broken shim
# cannot block shutdown.
#
# ``WorkingDirectory`` is intentionally set to /tmp so Python
# does not auto-prepend the release directory into
# ``sys.path[0]`` and shadow the installed wheel under
# site-packages (the same reasoning as the inline Python in
# ``promote_release.sh``'s provenance gate).
SHORT_SHA="${SHA:0:12}"
RELEASE_PY="$RELEASE_DIR/.venv/bin/python"

cat > "$DROPIN_FILE" <<EOF
# $UNIT_DESCRIPTION $SHORT_SHA
# using $RELEASE_DIR (release-local .venv, immutable).
# Drop-in precedence (10-release-*) wins over the older deploy-main-*
# drop-ins and over pre-existing evaluator/route-approval/router/
# tailscale-origin drop-ins; their Environment*= lines stay in place.
[Service]
WorkingDirectory=/tmp
# Supervisor pre-start gate. Runs as the release's own Python so
# ``omnigent`` imports from this release's venv (not from the main
# checkout). Aborts systemd startup on failure.
ExecStartPre=$RELEASE_PY -P -m omnigent.deploy.supervisor.gate
EOF

case "$SERVICE_KIND" in
    web)
        cat >> "$DROPIN_FILE" <<EOF
ExecStart=
ExecStart=$RELEASE_PY -P -m omnigent server \\
  --host 127.0.0.1 --port 4097 \\
  --no-open \\
  --config /home/hermes/.omnigent/config.yaml
EOF
        ;;
    host)
        SERVER_URL="http://127.0.0.1:4097"
        cat >> "$DROPIN_FILE" <<EOF
ExecStart=
ExecStart=$RELEASE_PY -P -m omnigent host --server $SERVER_URL
# Clean shutdown. systemd only invokes ExecStopPost on success,
# so a missing handler (e.g. an older release whose ``omni``
# shebang was broken) cannot block shutdown.
ExecStopPost=-$RELEASE_PY -P -m omnigent host stop --server $SERVER_URL
EOF
        ;;
esac

cat >> "$DROPIN_FILE" <<EOF
Environment=OMNIGENT_RELEASE_DIR=$RELEASE_DIR
Environment=OMNIGENT_RELEASE_EXPECTED_SHA=$SHA
Environment=PYTHONSAFEPATH=1
EOF

chmod 0644 "$DROPIN_FILE"
printf '%s\n' "$DROPIN_FILE"